---
name: "Bug report"
description: Create a report to help us improve
labels: "bug"
body:
  - type: checkboxes
    attributes:
      label: Before you submit a new bug report, please check that
      options:
        - label: I have read [frequently asked questions and limitations](https://github.com/bruxy70/Holidays/wiki/Review-before-submitting-a-new-issue-or-feature-request)
          required: true
        - label: I'm running the newest version of Holidays, or the next pre-release.
          required: true
        - label: I have enabled debug logging for my installation.
          required: true
  - type: textarea
    attributes:
      label: "Describe the bug"
      description: "Please provide a clear and concise description of what the bug is, including the steps to reproduce.
      Include screenshots to illustrate the issus."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Configuration"
      description: "Copy the device configuration below.
      Go to the device (e.g. from `Configuration` / `Devices & Services`, select the integration and the device.
      Hit `DOWNLOAD DIAGNOSTICS`, and paste the content of the file below."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Debug logs"
      description: "Copy the error message from Developer tools/Logs below.
      To enable debug logging, add `custom_components.holidays: debug`` 
      to your `configuration.yaml` under `logger`/`logs`."
      render: text
    validations:
      required: true
